import CryptoKit
import Foundation

/// Normalizes the list spellings used by subscription producers into the one
/// representation Tower stores. Clash YAML commonly writes `[h3]` or
/// `["h2", "http/1.1"]`, while share URIs use `h3` or repeated/comma joined
/// values. Keeping brackets or quotes in an entry changes the TLS protocol
/// name and makes an otherwise valid node fail its handshake.
enum ALPNList {
    static func values<S: Sequence>(_ rawValues: S) -> [String] where S.Element == String {
        rawValues.flatMap { rawValue in
            rawValue
                .trimmingCharacters(in: CharacterSet(charactersIn: "[] \t\r\n\"'"))
                .split(separator: ",", omittingEmptySubsequences: true)
                .map { $0.trimmingCharacters(in: CharacterSet(charactersIn: " \t\r\n\"'")) }
                .filter { !$0.isEmpty }
        }
    }

    static func values(_ rawValue: String?) -> [String] {
        guard let rawValue else { return [] }
        return values([rawValue])
    }

    static func normalized<S: Sequence>(_ rawValues: S) -> String? where S.Element == String {
        let entries = values(rawValues)
        return entries.isEmpty ? nil : entries.joined(separator: ",")
    }

    static func normalized(_ rawValue: String?) -> String? {
        guard let rawValue else { return nil }
        return normalized([rawValue])
    }
}

enum AppTab: String, CaseIterable, Identifiable {
    case subscriptions
    case rules
    case export

    var id: String { rawValue }

    var title: String {
        switch self {
        case .subscriptions: String(localized: "订阅")
        case .rules: String(localized: "规则")
        case .export: String(localized: "导出")
        }
    }

    var symbol: String {
        switch self {
        case .subscriptions: "antenna.radiowaves.left.and.right"
        case .rules: "point.3.connected.trianglepath.dotted"
        case .export: "arrow.up.forward.app"
        }
    }
}

struct SubscriptionSource: Identifiable, Codable, Hashable {
    let id: UUID
    var name: String
    var urlString: String
    var isEnabled: Bool
    var createdAt: Date
    var lastUpdatedAt: Date?
    var lastError: String?
    /// Plan usage reported by the airport, when it reports any.
    var usage: SubscriptionUsage?
    /// Optional request identity and encrypted resolver used by airports that
    /// reject generic clients or are not reachable through the system DNS.
    var requestOptions: SubscriptionRequestOptions?
    /// Nil keeps snapshots written before automatic provider naming compatible.
    /// Only automatically generated names may later be replaced by a provider's
    /// `Profile-Title`; an explicit name typed by the user is never overwritten.
    var nameWasAutoGenerated: Bool?

    init(
        id: UUID = UUID(),
        name: String,
        urlString: String,
        isEnabled: Bool = true,
        createdAt: Date = .now,
        lastUpdatedAt: Date? = nil,
        lastError: String? = nil,
        usage: SubscriptionUsage? = nil,
        requestOptions: SubscriptionRequestOptions? = nil,
        nameWasAutoGenerated: Bool? = nil
    ) {
        self.id = id
        self.name = name
        self.urlString = urlString
        self.isEnabled = isEnabled
        self.createdAt = createdAt
        self.lastUpdatedAt = lastUpdatedAt
        self.lastError = lastError
        self.usage = usage
        self.requestOptions = requestOptions
        self.nameWasAutoGenerated = nameWasAutoGenerated
    }

    var safeHost: String {
        URL(string: urlString)?.host ?? String(localized: "私密订阅")
    }
}

struct SubscriptionRequestOptions: Codable, Hashable, Sendable {
    var userAgent: String?
    var dnsOverHTTPSURL: String?

    init(userAgent: String? = nil, dnsOverHTTPSURL: String? = nil) {
        self.userAgent = Self.nonEmpty(userAgent)
        self.dnsOverHTTPSURL = Self.nonEmpty(dnsOverHTTPSURL)
    }

    var isEmpty: Bool { userAgent == nil && dnsOverHTTPSURL == nil }

    func validatedDNSOverHTTPSURL() throws -> URL? {
        guard let value = Self.nonEmpty(dnsOverHTTPSURL) else { return nil }
        guard let url = URL(string: value),
              url.scheme?.lowercased() == "https",
              url.host != nil else {
            throw SubscriptionError.invalidDNSURL
        }
        return url
    }

    private static func nonEmpty(_ value: String?) -> String? {
        let trimmed = value?.trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
        return trimmed.isEmpty ? nil : trimmed
    }
}

/// How much of an airport's plan is left.
///
/// Airports report this three different ways and Tower reads all of them: the
/// `subscription-userinfo` response header, a `STATUS=` line at the head of the
/// node list, and plain sentences smuggled into the list as fake entries. Which
/// one arrives varies by airport and, on at least one panel, by request.
struct SubscriptionUsage: Codable, Hashable, Sendable {
    var uploadBytes: Int64?
    var downloadBytes: Int64?
    var totalBytes: Int64?
    var expiresAt: Date?
    /// Text the airport wrote into the node list, kept verbatim because it is
    /// free-form and often says more than the header does.
    var notices: [String] = []

    var isEmpty: Bool {
        totalBytes == nil && expiresAt == nil && notices.isEmpty
    }

    /// Whether the plan is known in numbers rather than only in prose.
    /// Free-form notices are worth showing but cannot drive a progress bar.
    var hasPlanDetail: Bool {
        totalBytes != nil || expiresAt != nil
    }

    /// Notices that are worth showing beside the structured summary.
    ///
    /// Airports that send the header often *also* write the same numbers into
    /// the node list, so showing both prints the plan twice — once formatted by
    /// Tower and once in the airport's own wording. A notice is dropped only
    /// when the structured data already covers that exact fact; a reset
    /// countdown survives an expiry date because they are different dates.
    var distinctNotices: [String] {
        notices.filter { notice in
            let text = notice.lowercased()
            if totalBytes != nil, Self.trafficWords.contains(where: text.contains) { return false }
            if expiresAt != nil, Self.expiryWords.contains(where: text.contains) { return false }
            return true
        }
    }

    private static let trafficWords = ["流量", "traffic", "余额", "balance", "↑:", "↓:", "tot:"]
    private static let expiryWords = ["到期", "过期", "有效期至", "expire"]

    var usedBytes: Int64? {
        guard uploadBytes != nil || downloadBytes != nil else { return nil }
        return (uploadBytes ?? 0) + (downloadBytes ?? 0)
    }

    var remainingBytes: Int64? {
        guard let totalBytes, let usedBytes else { return nil }
        return max(totalBytes - usedBytes, 0)
    }

    /// 0…1 for a progress bar, nil when the airport gave no total.
    var usedFraction: Double? {
        guard let totalBytes, totalBytes > 0, let usedBytes else { return nil }
        return min(Double(usedBytes) / Double(totalBytes), 1)
    }

    /// Parses `upload=1; download=2; total=3; expire=1735660800`.
    ///
    /// Every field is optional: airports omit whichever they do not track, and
    /// a header carrying only `expire` is still worth showing.
    static func parse(header: String) -> SubscriptionUsage? {
        var usage = SubscriptionUsage()
        var matched = false

        for pair in header.split(separator: ";") {
            let parts = pair.split(separator: "=", maxSplits: 1)
            guard parts.count == 2 else { continue }
            let key = parts[0].trimmingCharacters(in: .whitespaces).lowercased()
            let raw = parts[1].trimmingCharacters(in: .whitespaces)
            // Some airports send a float for byte counts.
            guard let value = Double(raw) else { continue }

            switch key {
            case "upload": usage.uploadBytes = Int64(value); matched = true
            case "download": usage.downloadBytes = Int64(value); matched = true
            case "total": usage.totalBytes = Int64(value); matched = true
            case "expire":
                // A zero expiry means "never", not 1970.
                if value > 0 { usage.expiresAt = Date(timeIntervalSince1970: value) }
                matched = true
            default: break
            }
        }
        return matched ? usage : nil
    }

    /// Parses `STATUS=🚀↑:20.02GB,↓:97.73GB,TOT:220GB💡EXPIRES:2026-08-09`.
    ///
    /// Some panels prepend this line to the node list instead of sending the
    /// header. It is human-formatted rather than specified, so parsing stays
    /// tolerant: every field is optional and unknown decoration is skipped.
    static func parse(statusLine: String) -> SubscriptionUsage? {
        let text = statusLine.hasPrefix(statusPrefix)
            ? String(statusLine.dropFirst(statusPrefix.count))
            : statusLine
        var usage = SubscriptionUsage()
        var matched = false

        if let value = bytes(after: "↑:", in: text) { usage.uploadBytes = value; matched = true }
        if let value = bytes(after: "↓:", in: text) { usage.downloadBytes = value; matched = true }
        if let value = bytes(after: "TOT:", in: text) { usage.totalBytes = value; matched = true }
        if let date = day(after: "EXPIRES:", in: text) { usage.expiresAt = date; matched = true }

        return matched ? usage : nil
    }

    static let statusPrefix = "STATUS="

    private static let unitMultipliers: [String: Double] = [
        "": 1, "b": 1,
        "k": 1024, "kb": 1024,
        "m": 1_048_576, "mb": 1_048_576,
        "g": 1_073_741_824, "gb": 1_073_741_824,
        "t": 1_099_511_627_776, "tb": 1_099_511_627_776
    ]

    /// Reads `20.02GB` out of whatever follows `marker`.
    private static func bytes(after marker: String, in text: String) -> Int64? {
        guard let range = text.range(of: marker) else { return nil }
        var digits = ""
        var unit = ""
        for character in text[range.upperBound...] {
            if character.isNumber || character == "." {
                // Digits after the unit belong to the next field.
                if !unit.isEmpty { break }
                digits.append(character)
            } else if character.isLetter {
                unit.append(character)
                if unit.count == 2 { break }
            } else {
                break
            }
        }
        guard let value = Double(digits), let multiplier = unitMultipliers[unit.lowercased()] else {
            return nil
        }
        return Int64(value * multiplier)
    }

    private static func day(after marker: String, in text: String) -> Date? {
        guard let range = text.range(of: marker) else { return nil }
        let formatter = DateFormatter()
        formatter.locale = Locale(identifier: "en_US_POSIX")
        formatter.timeZone = TimeZone(identifier: "UTC")
        formatter.dateFormat = "yyyy-MM-dd"
        return formatter.date(from: String(text[range.upperBound...].prefix(10)))
    }
}

enum ProxyKind: String, Codable, CaseIterable, Identifiable {
    case shadowsocks = "ss"
    case shadowsocksR = "ssr"
    case vmess
    case vless
    case trojan
    case hysteria
    case hysteria2
    case tuic
    case wireguard
    case anytls
    case snell
    case socks5
    case http
    case unknown

    var id: String { rawValue }

    var title: String {
        switch self {
        case .shadowsocks: "Shadowsocks"
        case .shadowsocksR: "ShadowsocksR"
        case .vmess: "VMess"
        case .vless: "VLESS"
        case .trojan: "Trojan"
        case .hysteria: "Hysteria"
        case .hysteria2: "Hysteria 2"
        case .tuic: "TUIC"
        case .wireguard: "WireGuard"
        case .anytls: "AnyTLS"
        case .snell: "Snell"
        case .socks5: "SOCKS5"
        case .http: "HTTP"
        case .unknown: String(localized: "未知协议")
        }
    }

    var symbol: String {
        switch self {
        case .shadowsocks, .shadowsocksR: "bolt.horizontal.circle.fill"
        case .vmess, .vless: "point.3.filled.connected.trianglepath.dotted"
        case .trojan: "shield.lefthalf.filled"
        case .hysteria, .hysteria2: "hare.fill"
        // TUIC is the low-latency QUIC option. Keep it distinct from the
        // Shadowsocks bolt while matching the filled, circular protocol icons
        // used by the export filter.
        case .tuic: "bolt.circle.fill"
        case .wireguard: "shield.checkered"
        case .anytls: "lock.shield.fill"
        // Snell is Surge's own protocol, so this echoes the rounded-square app
        // icon it ships under, with an S for the name. Not Surge's actual mark:
        // that is their trademark and this repository is public and MIT.
        case .snell: "s.square.fill"
        case .socks5, .http: "network"
        case .unknown: "questionmark.circle.fill"
        }
    }
}

struct ProxyNode: Identifiable, Codable, Hashable {
    let id: UUID
    var sourceID: UUID?
    var kind: ProxyKind
    var name: String
    var server: String
    var port: Int
    var cipher: String?
    var password: String?
    var uuid: String?
    var username: String?
    var transport: String?
    /// Transport-specific mode (currently XHTTP). Kept separate from the
    /// transport name so `xhttp;mode=packet-up` survives a round trip.
    var transportMode: String?
    /// SIP003 plugin used by Shadowsocks. simple-obfs continues to use
    /// `obfs`; this field distinguishes v2ray-plugin from ordinary SS obfs.
    var plugin: String?
    var tls: Bool
    var sni: String?
    var hostHeader: String?
    var path: String?
    var alpn: String?
    /// REALITY's server public key (`pbk`) and short id (`sid`), plus the uTLS
    /// fingerprint (`fp`) and the XTLS flow. A VLESS node that carries these is
    /// a REALITY node: writing it without them yields plain TLS to a borrowed
    /// SNI, which looks fine and never connects.
    var realityPublicKey: String?
    var realityShortID: String?
    /// SHA-256 fingerprint of the server certificate. This is deliberately
    /// separate from `fingerprint`, which is the browser-style uTLS ClientHello
    /// name (`chrome`, `safari`, ...). Mihomo and Shadowrocket accept both and
    /// confusing them produces a syntactically valid profile that cannot
    /// complete its TLS handshake.
    var certificateFingerprint: String?
    var fingerprint: String?
    var flow: String?
    var skipCertificateVerification: Bool
    var alterID: Int?
    var protocolName: String?
    var protocolParam: String?
    var obfs: String?
    var obfsParam: String?
    /// AnyTLS session maintenance controls. Values are seconds, matching the
    /// user-facing fields and Mihomo; sing-box serialises them as durations.
    var idleSessionCheckInterval: Int?
    var idleSessionTimeout: Int?
    var minIdleSession: Int?
    /// Snell's protocol version. It decides both what a client accepts and
    /// whether the node can carry UDP.
    var version: Int?
    /// TUIC's QUIC tuning. `congestionControl` is `bbr`/`cubic`/`new_reno`
    /// and `udpRelayMode` is `native`/`quic`; both are per-server choices the
    /// airport makes, so a wrong guess costs UDP or throughput.
    var congestionControl: String?
    var udpRelayMode: String?
    /// Alternate QUIC destination ports used by Hysteria 2 (and, where a
    /// producer supports it, TUIC). Providers call this `ports`, `mport`,
    /// `server-ports`, or `port-hopping`; using only the display `port` makes
    /// most hops unreachable.
    var portHopping: String?
    /// Hysteria 1's bandwidth budget in Mbps. Unlike Hysteria 2 these are not
    /// optional hints: the protocol's congestion control is rate-based, so a
    /// node without them either fails to load or crawls.
    var upMbps: Int?
    var downMbps: Int?
    /// WireGuard's complete single-peer tunnel configuration. These cannot be
    /// mapped onto generic proxy credentials without losing routing semantics,
    /// so they stay explicit all the way from parser to client producer.
    var wireGuardPrivateKey: String?
    var wireGuardPublicKey: String?
    var wireGuardPreSharedKey: String?
    var wireGuardIPv4: String?
    var wireGuardIPv6: String?
    var wireGuardAllowedIPs: String?
    var wireGuardReserved: String?
    var wireGuardMTU: Int?
    var wireGuardPersistentKeepalive: Int?
    var wireGuardDNS: String?
    var rawURI: String
    /// Airports often encode quota, expiry, web site, or support text as fake
    /// proxy entries. Keeping the marker optional preserves old snapshots while
    /// letting Settings decide whether those entries remain visible/exported.
    var isSubscriptionMetadata: Bool?

    init(
        id: UUID = UUID(),
        sourceID: UUID? = nil,
        kind: ProxyKind,
        name: String,
        server: String,
        port: Int,
        cipher: String? = nil,
        password: String? = nil,
        uuid: String? = nil,
        username: String? = nil,
        transport: String? = nil,
        transportMode: String? = nil,
        plugin: String? = nil,
        tls: Bool = false,
        sni: String? = nil,
        hostHeader: String? = nil,
        path: String? = nil,
        alpn: String? = nil,
        realityPublicKey: String? = nil,
        realityShortID: String? = nil,
        certificateFingerprint: String? = nil,
        fingerprint: String? = nil,
        flow: String? = nil,
        skipCertificateVerification: Bool = false,
        alterID: Int? = nil,
        protocolName: String? = nil,
        protocolParam: String? = nil,
        obfs: String? = nil,
        obfsParam: String? = nil,
        idleSessionCheckInterval: Int? = nil,
        idleSessionTimeout: Int? = nil,
        minIdleSession: Int? = nil,
        version: Int? = nil,
        congestionControl: String? = nil,
        udpRelayMode: String? = nil,
        portHopping: String? = nil,
        upMbps: Int? = nil,
        downMbps: Int? = nil,
        wireGuardPrivateKey: String? = nil,
        wireGuardPublicKey: String? = nil,
        wireGuardPreSharedKey: String? = nil,
        wireGuardIPv4: String? = nil,
        wireGuardIPv6: String? = nil,
        wireGuardAllowedIPs: String? = nil,
        wireGuardReserved: String? = nil,
        wireGuardMTU: Int? = nil,
        wireGuardPersistentKeepalive: Int? = nil,
        wireGuardDNS: String? = nil,
        rawURI: String,
        isSubscriptionMetadata: Bool? = nil
    ) {
        self.id = id
        self.sourceID = sourceID
        self.kind = kind
        self.name = name
        self.server = server
        self.port = port
        self.cipher = cipher
        self.password = password
        self.uuid = uuid
        self.username = username
        self.transport = transport
        self.transportMode = transportMode
        self.plugin = plugin
        self.tls = tls
        self.sni = sni
        self.hostHeader = hostHeader
        self.path = path
        self.alpn = alpn
        self.realityPublicKey = realityPublicKey
        self.realityShortID = realityShortID
        self.certificateFingerprint = certificateFingerprint
        self.fingerprint = fingerprint
        self.flow = flow
        self.skipCertificateVerification = skipCertificateVerification
        self.alterID = alterID
        self.protocolName = protocolName
        self.protocolParam = protocolParam
        self.obfs = obfs
        self.obfsParam = obfsParam
        self.idleSessionCheckInterval = idleSessionCheckInterval
        self.idleSessionTimeout = idleSessionTimeout
        self.minIdleSession = minIdleSession
        self.version = version
        self.congestionControl = congestionControl
        self.udpRelayMode = udpRelayMode
        self.portHopping = portHopping
        self.upMbps = upMbps
        self.downMbps = downMbps
        self.wireGuardPrivateKey = wireGuardPrivateKey
        self.wireGuardPublicKey = wireGuardPublicKey
        self.wireGuardPreSharedKey = wireGuardPreSharedKey
        self.wireGuardIPv4 = wireGuardIPv4
        self.wireGuardIPv6 = wireGuardIPv6
        self.wireGuardAllowedIPs = wireGuardAllowedIPs
        self.wireGuardReserved = wireGuardReserved
        self.wireGuardMTU = wireGuardMTU
        self.wireGuardPersistentKeepalive = wireGuardPersistentKeepalive
        self.wireGuardDNS = wireGuardDNS
        self.rawURI = rawURI
        self.isSubscriptionMetadata = isSubscriptionMetadata
    }

    var endpoint: String {
        let host = server.contains(":") && !(server.hasPrefix("[") && server.hasSuffix("]"))
            ? "[\(server)]"
            : server
        return "\(host):\(port)"
    }
    var canonicalKey: String {
        // Shared front doors are common: an airport may publish many named
        // routes through the same host, port and credential. Those are still
        // distinct nodes when their display name, SNI, transport or other
        // connection parameters differ. Use the complete parsed identity so
        // only an exact repeated node is collapsed.
        var fields = [kind.rawValue, name, server.lowercased(), String(port)]
        fields.append(contentsOf: [cipher ?? "", password ?? "", uuid ?? "", username ?? ""])
        fields.append(contentsOf: [
            transport ?? "", transportMode ?? "", plugin ?? "", tls ? "1" : "0",
            sni ?? "", hostHeader ?? "", path ?? "", alpn ?? ""
        ])
        fields.append(contentsOf: [
            realityPublicKey ?? "", realityShortID ?? "", fingerprint ?? "", flow ?? "",
            skipCertificateVerification ? "1" : "0"
        ])
        fields.append(contentsOf: [
            alterID.map(String.init) ?? "", protocolName ?? "", protocolParam ?? "",
            obfs ?? "", obfsParam ?? ""
        ])
        let idleCheck = idleSessionCheckInterval.map { String($0) } ?? ""
        let idleTimeout = idleSessionTimeout.map { String($0) } ?? ""
        let minimumIdle = minIdleSession.map { String($0) } ?? ""
        let protocolVersion = version.map { String($0) } ?? ""
        fields.append(contentsOf: [certificateFingerprint ?? "", idleCheck, idleTimeout, minimumIdle, protocolVersion])
        fields.append(contentsOf: [
            congestionControl ?? "", udpRelayMode ?? "", portHopping ?? "",
            upMbps.map(String.init) ?? "", downMbps.map(String.init) ?? ""
        ])
        let wireGuardFields: [String] = [
            wireGuardPrivateKey ?? "", wireGuardPublicKey ?? "", wireGuardPreSharedKey ?? "",
            wireGuardIPv4 ?? "", wireGuardIPv6 ?? "", wireGuardAllowedIPs ?? "",
            wireGuardReserved ?? "", wireGuardMTU.map { String($0) } ?? "",
            wireGuardPersistentKeepalive.map { String($0) } ?? "", wireGuardDNS ?? ""
        ]
        fields.append(contentsOf: wireGuardFields)
        return fields.joined(separator: "\u{1F}")
    }

    /// Whether this node negotiates REALITY rather than ordinary TLS.
    var usesReality: Bool {
        !(realityPublicKey ?? "").isEmpty
    }

    /// The VMess/VLESS id in the form every client accepts.
    ///
    /// Xray lets the id be any string shorter than 32 bytes and derives a v5
    /// UUID from it — SHA-1 over the nil namespace followed by the text — so
    /// airports do publish ids like `abcd1234`. Clash and Stash refuse anything
    /// that is not a UUID (`invalid UUID length: 8`) and will not load the file
    /// at all, so the same derivation is done here. The server compares against
    /// exactly this value, so the node still connects.
    var exportableUUID: String? {
        guard let uuid else { return nil }
        return ProxyNode.normalizedProxyID(uuid)
    }

    /// The transport path in the form a client will accept.
    ///
    /// WebSocket and HTTP/2 paths are HTTP request paths, so they have to be
    /// absolute, but airports do publish them without the leading slash. Xray's
    /// own server prepends one before matching (`GetNormalizedPath`), so doing
    /// the same here is what the node was always going to send on the wire.
    /// Clash and Shadowrocket quietly normalise it; Surge rejects the whole
    /// profile with "字段 `ws-path` 的值无效".
    var exportablePath: String? {
        guard let path, !path.isEmpty else { return nil }
        return path.hasPrefix("/") ? path : "/" + path
    }

    static func normalizedProxyID(_ value: String) -> String? {
        let trimmed = value.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return nil }
        if UUID(uuidString: trimmed) != nil { return trimmed }
        // Xray's own bound: 32 bytes or more is treated as a malformed UUID
        // rather than a name, and there is nothing faithful to emit for it.
        guard trimmed.utf8.count < 32 else { return nil }
        return derivedUUID(from: trimmed)
    }

    private static func derivedUUID(from text: String) -> String {
        var hasher = Insecure.SHA1()
        hasher.update(data: Data(repeating: 0, count: 16))
        hasher.update(data: Data(text.utf8))
        var bytes = Array(hasher.finalize().prefix(16))
        bytes[6] = (bytes[6] & 0x0F) | (5 << 4)
        bytes[8] = (bytes[8] & 0x3F) | 0x80
        return UUID(uuid: (
            bytes[0], bytes[1], bytes[2], bytes[3], bytes[4], bytes[5], bytes[6], bytes[7],
            bytes[8], bytes[9], bytes[10], bytes[11], bytes[12], bytes[13], bytes[14], bytes[15]
        )).uuidString.lowercased()
    }
    var isLocal: Bool { sourceID == nil }

    var protocolSummary: String {
        var parts: [String] = [protocolDisplayName]

        if let transportDisplayName, !parts.contains(transportDisplayName) {
            parts.append(transportDisplayName)
        }

        if tls, ![.trojan, .hysteria, .hysteria2, .tuic, .wireguard, .anytls, .http].contains(kind), !parts.contains("TLS") {
            parts.append("TLS")
        }

        if supportsUDP {
            parts.append("UDP")
        }
        return parts.joined(separator: " / ")
    }

    private var protocolDisplayName: String {
        switch kind {
        case .shadowsocks: "SHADOWSOCKS"
        case .shadowsocksR: "SHADOWSOCKS R"
        case .vmess: "VMESS"
        case .vless: "VLESS"
        case .trojan: "TROJAN"
        case .hysteria: "HYSTERIA"
        case .hysteria2: "HYSTERIA 2"
        case .tuic: "TUIC"
        case .wireguard: "WIREGUARD"
        case .anytls: "ANYTLS"
        case .snell: version.map { "SNELL V\($0)" } ?? "SNELL"
        case .socks5: "SOCKS5"
        case .http: tls ? "HTTPS" : "HTTP"
        case .unknown: "未知协议"
        }
    }

    private var transportDisplayName: String? {
        let rawTransport: String?
        if let transport, !transport.isEmpty {
            rawTransport = transport
        } else if [.shadowsocks, .shadowsocksR].contains(kind),
                  let obfs, !obfs.isEmpty, obfs.lowercased() != "plain" {
            rawTransport = obfs
        } else {
            rawTransport = nil
        }

        guard let normalized = rawTransport?
            .trimmingCharacters(in: .whitespacesAndNewlines)
            .lowercased(),
            !["", "tcp", "none", "plain"].contains(normalized) else {
            return nil
        }

        return switch normalized {
        case "ws", "websocket": "WS"
        case "grpc": "GRPC"
        case "http", "http_simple": "HTTP"
        case "h2", "http2": "H2"
        case "httpupgrade": "HTTP UPGRADE"
        case "xhttp", "splithttp": "XHTTP"
        case "kcp", "mkcp": "KCP"
        case "quic": "QUIC"
        case "tls1.2_ticket_auth", "tls": "TLS"
        default: normalized.uppercased()
        }
    }

    private var supportsUDP: Bool {
        switch kind {
        case .http, .unknown: false
        // Snell only carries UDP from version 3 onwards.
        case .snell: (version ?? 4) >= 3
        default: true
        }
    }
}

enum RulePolicy: String, Codable, Hashable {
    case direct
    case reject
    case select
    case auto
    case international
    case domestic
    case foreignAds
    case ai
    case youtube
    case media
    case telegram
    case googleFCM
    case apple
    case microsoft
    case google

    var displayName: String {
        switch self {
        case .direct: String(localized: "全球直连")
        case .reject: String(localized: "广告拦截")
        case .select: String(localized: "节点选择")
        case .auto: String(localized: "自动选择")
        case .international: String(localized: "国际流量")
        case .domestic: String(localized: "国内流量")
        case .foreignAds: String(localized: "国外广告")
        case .ai: String(localized: "AI 服务")
        case .youtube: "YouTube"
        case .media: String(localized: "国外媒体")
        case .telegram: "Telegram"
        case .googleFCM: "Google FCM"
        case .apple: String(localized: "苹果服务")
        case .microsoft: String(localized: "微软服务")
        case .google: String(localized: "谷歌服务")
        }
    }

    var configurationName: String {
        switch self {
        case .direct: "DIRECT"
        case .reject: "REJECT"
        case .select: "节点选择"
        case .auto: "自动选择"
        case .international: "国际流量"
        case .domestic: "国内流量"
        case .foreignAds: "国外广告"
        case .ai: "AI服务"
        case .youtube: "YouTube"
        case .media: "国外媒体"
        case .telegram: "Telegram"
        case .googleFCM: "Google FCM"
        case .apple: "苹果服务"
        case .microsoft: "Microsoft"
        case .google: "谷歌服务"
        }
    }
}

struct RuleAssignment: Identifiable, Codable, Hashable {
    var id: String { resourcePath }
    let resourcePath: String
    let title: String
    let policy: RulePolicy
}

struct RulePreset: Identifiable, Codable, Hashable {
    let id: String
    let name: String
    let summary: String
    let symbol: String
    let tintName: String
    let assignments: [RuleAssignment]
    let includeGeoIPCN: Bool
    let finalPolicy: RulePolicy
    let isRecommended: Bool

    var policies: [RulePolicy] {
        var result: [RulePolicy] = [.select, .auto]
        for assignment in assignments where !result.contains(assignment.policy) {
            result.append(assignment.policy)
        }
        if !result.contains(finalPolicy) { result.append(finalPolicy) }
        return result
    }

    static let builtIns: [RulePreset] = [
        RulePreset(
            id: "self-configuration",
            name: "Self-Configuration",
            summary: String(localized: "AI、全球流媒体、广告过滤和国内外流量精细分流。"),
            symbol: "point.3.connected.trianglepath.dotted",
            tintName: "blue",
            assignments: [
                .init(resourcePath: "AdBlock", title: "AdBlock", policy: .foreignAds),
                .init(resourcePath: "HTTPDNS", title: "HTTPDNS", policy: .foreignAds),
                .init(resourcePath: "Special", title: "特殊直连", policy: .direct),
                .init(resourcePath: "AI Suite", title: "AI Suite", policy: .ai),
                .init(resourcePath: "Netflix", title: "Netflix", policy: .media),
                .init(resourcePath: "Disney Plus", title: "Disney+", policy: .media),
                .init(resourcePath: "YouTube", title: "YouTube", policy: .youtube),
                .init(resourcePath: "Max", title: "Max", policy: .media),
                .init(resourcePath: "Spotify", title: "Spotify", policy: .media),
                .init(resourcePath: "Bilibili", title: "哔哩哔哩", policy: .domestic),
                .init(resourcePath: "IQ", title: "iQI", policy: .domestic),
                .init(resourcePath: "IQIYI", title: "爱奇艺", policy: .domestic),
                .init(resourcePath: "Letv", title: "乐视", policy: .domestic),
                .init(resourcePath: "Netease Music", title: "网易云音乐", policy: .domestic),
                .init(resourcePath: "Tencent Video", title: "腾讯视频", policy: .domestic),
                .init(resourcePath: "WeTV", title: "WeTV", policy: .domestic),
                .init(resourcePath: "Youku", title: "优酷", policy: .domestic),
                .init(resourcePath: "Abema TV", title: "Abema TV", policy: .media),
                .init(resourcePath: "Bahamut", title: "巴哈姆特", policy: .media),
                .init(resourcePath: "DMM", title: "DMM", policy: .media),
                .init(resourcePath: "Fox+", title: "Fox+", policy: .media),
                .init(resourcePath: "Hulu Japan", title: "Hulu Japan", policy: .media),
                .init(resourcePath: "Japonx", title: "Japonx", policy: .media),
                .init(resourcePath: "JOOX", title: "JOOX", policy: .media),
                .init(resourcePath: "KKBOX", title: "KKBOX", policy: .media),
                .init(resourcePath: "KKTV", title: "KKTV", policy: .media),
                .init(resourcePath: "Line TV", title: "Line TV", policy: .media),
                .init(resourcePath: "myTV SUPER", title: "myTV SUPER", policy: .media),
                .init(resourcePath: "Niconico", title: "Niconico", policy: .media),
                .init(resourcePath: "ViuTV", title: "ViuTV", policy: .media),
                .init(resourcePath: "ABC", title: "ABC", policy: .media),
                .init(resourcePath: "Amazon", title: "Amazon", policy: .media),
                .init(resourcePath: "BBC iPlayer", title: "BBC iPlayer", policy: .media),
                .init(resourcePath: "DAZN", title: "DAZN", policy: .media),
                .init(resourcePath: "Discovery Plus", title: "Discovery+", policy: .media),
                .init(resourcePath: "encoreTVB", title: "encoreTVB", policy: .media),
                .init(resourcePath: "F1 TV", title: "F1 TV", policy: .media),
                .init(resourcePath: "Fox Now", title: "Fox Now", policy: .media),
                .init(resourcePath: "Hulu", title: "Hulu", policy: .media),
                .init(resourcePath: "Pandora", title: "Pandora", policy: .media),
                .init(resourcePath: "PBS", title: "PBS", policy: .media),
                .init(resourcePath: "Pornhub", title: "Pornhub", policy: .media),
                .init(resourcePath: "Soundcloud", title: "SoundCloud", policy: .media),
                .init(resourcePath: "Telegram", title: "Telegram", policy: .telegram),
                .init(resourcePath: "Crypto", title: "加密货币", policy: .international),
                .init(resourcePath: "Discord", title: "Discord", policy: .international),
                .init(resourcePath: "Google FCM", title: "Google FCM", policy: .googleFCM),
                .init(resourcePath: "Google", title: "Google", policy: .google),
                .init(resourcePath: "Google Drive", title: "Google Drive", policy: .google),
                .init(resourcePath: "YouTube Music", title: "YouTube Music", policy: .youtube),
                .init(resourcePath: "Google Search", title: "Google Search", policy: .google),
                .init(resourcePath: "Microsoft", title: "Microsoft", policy: .microsoft),
                .init(resourcePath: "PayPal", title: "PayPal", policy: .international),
                .init(resourcePath: "Scholar", title: "Google Scholar", policy: .google),
                .init(resourcePath: "Speedtest", title: "Speedtest", policy: .international),
                .init(resourcePath: "Steam", title: "Steam", policy: .international),
                .init(resourcePath: "TikTok", title: "TikTok", policy: .international),
                .init(resourcePath: "Apple Music", title: "Apple Music", policy: .apple),
                .init(resourcePath: "Apple News", title: "Apple News", policy: .apple),
                .init(resourcePath: "Apple TV", title: "Apple TV", policy: .apple),
                .init(resourcePath: "Apple", title: "Apple 服务", policy: .apple),
                .init(resourcePath: "miHoYo", title: "米哈游", policy: .domestic),
                .init(resourcePath: "PROXY", title: "国际代理", policy: .international),
                .init(resourcePath: "Domestic", title: "国内域名", policy: .domestic),
                .init(resourcePath: "Domestic IPs", title: "国内 IP", policy: .domestic),
                .init(resourcePath: "LAN", title: "局域网", policy: .direct),
                .init(resourcePath: "GeoIP CN", title: "中国大陆 GeoIP", policy: .domestic)
            ],
            includeGeoIPCN: false,
            finalPolicy: .international,
            isRecommended: true
        )
    ]
}

enum ClientTarget: String, CaseIterable, Identifiable, Codable {
    case surge
    case clash
    case shadowrocket
    case loon
    case quanx
    case hiddify
    case egern

    var id: String { rawValue }

    var name: String {
        switch self {
        case .surge: "Surge"
        case .clash: "Stash"
        case .shadowrocket: "Shadowrocket"
        case .loon: "Loon"
        case .quanx: "QuanX"
        case .hiddify: "Hiddify"
        case .egern: "Egern"
        }
    }

    var subtitle: String {
        switch self {
        case .surge: String(localized: "完整配置")
        case .clash: "Clash YAML"
        case .shadowrocket: String(localized: "本地配置")
        case .loon: String(localized: "完整配置")
        case .quanx: "Quantumult X"
        case .hiddify: String(localized: "sing-box 内核")
        case .egern: "Egern YAML"
        }
    }

    var symbol: String {
        switch self {
        case .surge: "wave.3.right.circle.fill"
        case .clash: "square.3.layers.3d.top.filled"
        case .shadowrocket: "paperplane.circle.fill"
        case .loon: "moon.stars.circle.fill"
        case .quanx: "q.circle.fill"
        case .hiddify: "eye.slash.circle.fill"
        case .egern: "e.circle.fill"
        }
    }

    /// Official App Store artwork used only to identify the user's chosen
    /// installed client. Optional keeps a safe SF Symbol fallback.
    var appIconAssetName: String? {
        switch self {
        case .surge: "ClientSurge"
        case .clash: "ClientStash"
        case .shadowrocket: "ClientShadowrocket"
        case .loon: "ClientLoon"
        case .quanx: "ClientQuantumultX"
        case .hiddify: "ClientHiddify"
        case .egern: "ClientEgern"
        }
    }

    var brandSymbol: String {
        switch self {
        case .surge: "waveform.path.ecg"
        case .clash: "square.3.layers.3d.top.filled"
        case .shadowrocket: "paperplane.fill"
        case .loon: "moon.stars.fill"
        case .quanx: "q.circle.fill"
        case .hiddify: "shield.lefthalf.filled"
        case .egern: "e.circle.fill"
        }
    }

    var brandColorHex: String {
        switch self {
        case .surge: "3157D5"
        case .clash: "1473E6"
        case .shadowrocket: "1B98F5"
        case .loon: "6B45D8"
        case .quanx: "14A69A"
        case .hiddify: "6047D9"
        case .egern: "F08A2B"
        }
    }

    /// Whether the client has fields for REALITY's public key and short id.
    ///
    /// Only Surge does not: its producer raises `reality is unsupported`
    /// outright, and it takes no VLESS at all, which is the only protocol
    /// Tower sees REALITY on. Everything else carries it, Shadowrocket
    /// included.
    var expressesReality: Bool {
        self != .surge
    }

    /// Hiddify is a Flutter shell over hiddify-core, which is sing-box, so it
    /// reads a sing-box document. sing-box ships no App Store client of its
    /// own, so the format is offered only under the app that actually runs it.
    var usesSingBoxFormat: Bool {
        self == .hiddify
    }

    var fileExtension: String {
        switch self {
        case .clash, .egern: "yaml"
        case .hiddify: "json"
        default: "conf"
        }
    }

    var supportsDirectConfigurationImport: Bool {
        // Quantumult X is the only one left without an install scheme.
        switch self {
        case .quanx: false
        default: true
        }
    }

    var supportsNodesOnlyImport: Bool {
        [.shadowrocket, .loon, .quanx, .hiddify].contains(self)
    }

    func supportsDirectImport(mode: ExportContentMode) -> Bool {
        switch mode {
        case .fullConfiguration: supportsDirectConfigurationImport
        case .nodesOnly: supportsNodesOnlyImport
        // Quantumult X has remote node and filter resources, but policy groups
        // only exist in the full configuration's [policy] section. A filter
        // resource alone can therefore reference policy names that do not
        // exist, so Tower never presents it as a complete import operation.
        case .rulesOnly: false
        }
    }

    var supportedContentModes: [ExportContentMode] {
        guard supportsNodesOnlyImport else { return [.fullConfiguration] }
        return [.fullConfiguration, .nodesOnly]
    }

    var primaryImportTitle: String {
        supportsDirectConfigurationImport
            ? String(localized: "一键导出到 \(name)")
            : String(localized: "用文件导出到 \(name)")
    }

    func supports(_ kind: ProxyKind) -> Bool {
        switch self {
        case .clash:
            kind != .unknown
        case .surge:
            // TUIC but no Hysteria 1: Surge writes `tuic-v5` and has never
            // shipped a Hysteria 1 server type.
            [.shadowsocks, .vmess, .trojan, .hysteria2, .tuic, .wireguard, .anytls, .snell, .socks5, .http].contains(kind)
        case .shadowrocket:
            kind != .unknown
        case .loon:
            // Neither TUIC nor Hysteria 1 has a Loon server type; both are
            // skipped and counted rather than written as something else.
            [.shadowsocks, .shadowsocksR, .vmess, .vless, .trojan, .hysteria2, .wireguard, .anytls, .socks5, .http].contains(kind)
        case .quanx:
            // No Hysteria 2: Quantumult X has no `hysteria2=` server type, and
            // writing one fails the whole import with "配置文件语法错误". Its
            // sample.conf documents ss2022, REALITY, vless-flow and AnyTLS but
            // no Hysteria at all.
            // TUIC and Hysteria 1 are absent for the same reason.
            [.shadowsocks, .shadowsocksR, .vmess, .vless, .trojan, .anytls, .socks5, .http].contains(kind)
        case .hiddify:
            // No Snell: sing-box the project implements it, but the core
            // Hiddify ships does not, so those nodes are skipped and counted.
            kind != .unknown && kind != .snell
        case .egern:
            // Egern's own producer lists tuic but no hysteria 1.
            [.shadowsocks, .vmess, .vless, .trojan, .hysteria2, .tuic, .wireguard, .anytls, .snell, .socks5, .http].contains(kind)
        }
    }
}

enum ExportContentMode: String, CaseIterable, Codable, Identifiable {
    case fullConfiguration
    case nodesOnly
    case rulesOnly

    var id: String { rawValue }

    var title: String {
        switch self {
        case .fullConfiguration: String(localized: "完整配置")
        case .nodesOnly: String(localized: "仅节点")
        // Kept for decoding older snapshots. No current client exposes this
        // mode because a remote rule resource cannot carry its policy groups.
        case .rulesOnly: String(localized: "本地规则")
        }
    }
}

enum ClientTargetOrder {
    static func normalized(rawValues: [String]?) -> [ClientTarget] {
        var seen = Set<ClientTarget>()
        var result: [ClientTarget] = []

        for rawValue in rawValues ?? [] {
            guard let target = ClientTarget(rawValue: rawValue), seen.insert(target).inserted else { continue }
            result.append(target)
        }
        for target in ClientTarget.allCases where seen.insert(target).inserted {
            result.append(target)
        }
        return result
    }
}

struct AppSnapshot: Codable {
    var subscriptions: [SubscriptionSource]
    var nodes: [ProxyNode]
    var selectedPresetID: String
    var selectedTarget: ClientTarget
    /// Optional so snapshots written before rule import still decode. The
    /// synthesised decoder does not fall back to default values for missing
    /// keys, so this must stay optional rather than default to an empty array.
    var importedSchemes: [RuleScheme]?
    /// Explicitly enabled service-rule groups per scheme. A missing scheme key
    /// keeps the upstream/default behavior of enabling every group.
    var selectedRuleGroups: [String: [String]]?
    /// Whether imported policy-group names keep their decorative leading emoji,
    /// keyed by scheme id. Missing entries preserve the source appearance.
    var ruleGroupEmojisEnabled: [String: Bool]?
    /// Nodes explicitly excluded from generated configurations. Optional keeps
    /// snapshots written before per-node selection backward compatible.
    var excludedNodeIDs: [UUID]?
    /// User-authored rules live outside downloaded schemes so upstream refresh
    /// can never overwrite them.
    var customRuleFlows: [CustomRuleFlow]?
    /// Protocols the user chose not to write, keyed by client raw value. Stored
    /// as plain strings because a dictionary with a non-String key encodes as a
    /// flat array, which is awkward to read in state.json.
    var excludedKinds: [String: [String]]?
    /// Optional for snapshots created before renewal reminders existed.
    var renewalRemindersEnabled: Bool?
    /// Raw values allow future versions to append new clients safely.
    var clientOrder: [String]?
    /// Optional settings keep every previously written snapshot decodable.
    var appendSubscriptionNameToNodes: Bool?
    var filterSubscriptionInfoNodes: Bool?
    /// Optional so snapshots written before automatic refresh existed decode
    /// unchanged, and so a missing value means off rather than on.
    var autoRefreshOnOpen: Bool?
    var configurationName: String?
    /// Prefer native remote rule-set references when the selected client and
    /// downloaded resource use compatible syntax. Missing means disabled.
    var preferRuleSets: Bool?
    /// The previous release briefly treated a missing preference as enabled.
    /// This marker lets that implicit value migrate back to the safer disabled
    /// default without overwriting a choice the user makes afterwards.
    var preferRuleSetsWasExplicitlySet: Bool?
    /// When this snapshot was written, used to decide which of two devices'
    /// copies wins. Optional so every snapshot written before iCloud sync
    /// existed still decodes; a missing value loses to any dated one, which is
    /// the right way round — a snapshot from before sync cannot have been the
    /// more recent edit on another device.
    var updatedAt: Date?
    /// Per-client import mode. New or unsupported clients fall back to full.
    var exportContentModes: [String: String]?

    init(
        subscriptions: [SubscriptionSource],
        nodes: [ProxyNode],
        selectedPresetID: String,
        selectedTarget: ClientTarget,
        importedSchemes: [RuleScheme]? = nil,
        selectedRuleGroups: [String: [String]]? = nil,
        ruleGroupEmojisEnabled: [String: Bool]? = nil,
        excludedNodeIDs: [UUID]? = nil,
        customRuleFlows: [CustomRuleFlow]? = nil,
        excludedKinds: [String: [String]]? = nil,
        renewalRemindersEnabled: Bool? = nil,
        clientOrder: [String]? = nil,
        appendSubscriptionNameToNodes: Bool? = nil,
        filterSubscriptionInfoNodes: Bool? = nil,
        autoRefreshOnOpen: Bool? = nil,
        configurationName: String? = nil,
        preferRuleSets: Bool? = nil,
        preferRuleSetsWasExplicitlySet: Bool? = nil,
        exportContentModes: [String: String]? = nil,
        updatedAt: Date? = nil
    ) {
        self.subscriptions = subscriptions
        self.nodes = nodes
        self.selectedPresetID = selectedPresetID
        self.selectedTarget = selectedTarget
        self.importedSchemes = importedSchemes
        self.selectedRuleGroups = selectedRuleGroups
        self.ruleGroupEmojisEnabled = ruleGroupEmojisEnabled
        self.excludedNodeIDs = excludedNodeIDs
        self.customRuleFlows = customRuleFlows
        self.excludedKinds = excludedKinds
        self.renewalRemindersEnabled = renewalRemindersEnabled
        self.clientOrder = clientOrder
        self.appendSubscriptionNameToNodes = appendSubscriptionNameToNodes
        self.filterSubscriptionInfoNodes = filterSubscriptionInfoNodes
        self.autoRefreshOnOpen = autoRefreshOnOpen
        self.configurationName = configurationName
        self.preferRuleSets = preferRuleSets
        self.preferRuleSetsWasExplicitlySet = preferRuleSetsWasExplicitlySet
        self.exportContentModes = exportContentModes
        self.updatedAt = updatedAt
    }
}

/// Deliberately carries no HTTP response metadata. The subscription response
/// headers usually include `subscription-userinfo` and session cookies, and
/// nothing in the app consumed them.
struct ImportResult: Sendable {
    let nodes: [ProxyNode]
    let rejectedLineCount: Int
    var usage: SubscriptionUsage?
    /// Provider supplied title from `Profile-Title`/Content-Disposition.
    var suggestedName: String? = nil
}

enum TowerBrand {
    static var localizedName: String {
        String(localized: "塔台")
    }

    static func migratedDefaultName(_ candidate: String?) -> String {
        let trimmed = candidate?.trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
        if ["Tower", "塔台", "塔臺"].contains(trimmed) { return localizedName }
        return ExportFilePresentation.profileName(trimmed)
    }
}

/// Keeps the subscription name typed by the user stable while the edit sheet
/// dismisses its focused text field. SwiftUI can publish one final empty value
/// during toolbar dismissal, which must not overwrite the last real input.
struct SubscriptionNameDraft: Equatable {
    var text: String {
        didSet {
            let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
            if !trimmed.isEmpty {
                lastValidText = text
            }
        }
    }
    private var lastValidText: String?

    init(text: String = "") {
        self.text = text
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        self.lastValidText = trimmed.isEmpty ? nil : text
    }

    var committedName: String {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        return (trimmed.isEmpty ? lastValidText : text)?
            .trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
    }
}

/// Keeps raw in-progress text separate from the persisted export name. An
/// empty draft is valid while editing; the default is restored only on commit.
struct ConfigurationNameDraft: Equatable {
    var text: String {
        didSet {
            let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
            if !trimmed.isEmpty {
                lastValidText = text
            }
        }
    }
    private var hasLoadedPersistedName = false
    /// SwiftUI can publish one transient empty string when a focused text
    /// field is dismissed from a parent toolbar. Keep the last value the user
    /// actually entered so that teardown event cannot reset a valid name.
    private var lastValidText: String?

    init(text: String = "") {
        self.text = text
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        self.lastValidText = trimmed.isEmpty ? nil : text
    }

    mutating func loadPersistedNameIfNeeded(_ name: String) {
        guard !hasLoadedPersistedName else { return }
        text = name
        hasLoadedPersistedName = true
    }

    var committedName: String {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        return ExportFilePresentation.profileName(trimmed.isEmpty ? lastValidText : text)
    }
}

enum ExportFilePresentation {
    static func profileName(_ candidate: String?) -> String {
        let trimmed = candidate?.trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
        let fallback = trimmed.isEmpty ? TowerBrand.localizedName : trimmed
        let forbidden = CharacterSet(charactersIn: "/:\\?%*|\"<>\0")
        let cleaned = fallback.components(separatedBy: forbidden).joined(separator: " ")
            .replacingOccurrences(of: "  ", with: " ")
            .trimmingCharacters(in: .whitespacesAndNewlines)
        return String((cleaned.isEmpty ? TowerBrand.localizedName : cleaned).prefix(80))
    }

    static func contentDisposition(fileName: String) -> String {
        let allowed = CharacterSet.alphanumerics.union(CharacterSet(charactersIn: "-._~"))
        let encoded = fileName.addingPercentEncoding(withAllowedCharacters: allowed) ?? fileName
        let fallback: String
        if fileName.canBeConverted(to: .ascii) {
            fallback = fileName
        } else {
            let fileExtension = (fileName as NSString).pathExtension
            fallback = fileExtension.isEmpty ? "Tower" : "Tower.\(fileExtension)"
        }
        return "attachment; filename=\"\(fallback)\"; filename*=UTF-8''\(encoded)"
    }
}

struct GeneratedConfiguration {
    let target: ClientTarget
    let content: String
    let supportedNodeCount: Int
    let skippedNodeCount: Int
    let ruleCount: Int
    let profileName: String
    let contentMode: ExportContentMode
    let fileExtensionOverride: String?

    init(
        target: ClientTarget,
        content: String,
        supportedNodeCount: Int,
        skippedNodeCount: Int,
        ruleCount: Int,
        profileName: String = TowerBrand.localizedName,
        contentMode: ExportContentMode = .fullConfiguration,
        fileExtensionOverride: String? = nil
    ) {
        self.target = target
        self.content = content
        self.supportedNodeCount = supportedNodeCount
        self.skippedNodeCount = skippedNodeCount
        self.ruleCount = ruleCount
        self.profileName = ExportFilePresentation.profileName(profileName)
        self.contentMode = contentMode
        self.fileExtensionOverride = fileExtensionOverride
    }

    var fileExtension: String { fileExtensionOverride ?? target.fileExtension }

    var fileName: String {
        "\(profileName).\(fileExtension)"
    }

    func named(_ value: String) -> GeneratedConfiguration {
        GeneratedConfiguration(
            target: target,
            content: content,
            supportedNodeCount: supportedNodeCount,
            skippedNodeCount: skippedNodeCount,
            ruleCount: ruleCount,
            profileName: value,
            contentMode: contentMode,
            fileExtensionOverride: fileExtensionOverride
        )
    }
}
